name: review-gravv-docs

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy custom styles and vocabularies
        run: cp -r .github/custom-styles/. .github/styles/

      - name: Run Vale
        uses: errata-ai/vale-action@v2.1.1
        with:
          files: ./docs
          sync: true

      - name: Delete Vale styles
        if: always()
        run: rm -rf .github/styles
